### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by marcoaccardi** [marcoaccardi/sileno#7]
`CUDACXX=/usr/local/cuda-12.3/bin/nvcc CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=native" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir --force-reinstall --upgrade
`
this command might be better for cuda 12.3

**Comment by gabacode** [comment]
Try to `ls -l /usr/local/` and you will see that cuda-12 it's just a link to your actual alternative version.
